name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    name: Ping Render service
    runs-on: ubuntu-latest

    steps:
      - name: Curl Render URL
        run: |
          curl -fsS https://grocery-server-i29t.onrender.com/api/categories || true
